resources:
  database:
    type: mysql
    options:
      storage: 10
  #queue:
  #  type: redis

environment:
  - ADMIN_URL

services:
  website:
    domain: www.${DOMAIN},${DOMAIN}
    build:
      manifest: ./backend_wordpress/wordpress/docker/Dockerfile
      # command: bin/api
    environment:
      - ADMIN_URL
      - WITH_FRONTEND
      - FRONTEND_URL
      - DEBUG
      - OFFLOAD_AWS_REGION
      - OFFLOAD_AWS_BUCKET
      - OFFLOAD_AWS_ACCESS_ID
      - OFFLOAD_AWS_SECRET
      # NEW RELIC
      - NEW_RELIC_APP_NAME
      - NEW_RELIC_LICENSE_KEY
      # JS
      - LB_API_TOKEN
      - LB_API_URL
    health: /test.html
    internal: false
    port: 8080
    resources:
      - database
    # - queue
    termination:
      grace: 45
    test: make test
    timeout: 120
    deployment:
      minimum: 50
      maximum: 200
    scale:
      targets:
        cpu: 70
        memory: 90
      count: 1-16
      cpu: 512
      memory: 1024
  cms:
    domain: cms.${DOMAIN}
    build:
      manifest: ./backend_wordpress/wordpress/docker/Dockerfile
      # command: bin/api
    environment:
      - ADMIN_URL
      - WITH_FRONTEND
      - FRONTEND_URL
      - DEBUG
      - OFFLOAD_AWS_REGION
      - OFFLOAD_AWS_BUCKET
      - OFFLOAD_AWS_ACCESS_ID
      - OFFLOAD_AWS_SECRET
      # NEW RELIC
      - NEW_RELIC_APP_NAME
      - NEW_RELIC_LICENSE_KEY
      # JS
      - LB_API_TOKEN
      - LB_API_URL
    health: /test.html
    internal: false
    port: 8080
    resources:
      - database
    # - queue
    termination:
      grace: 45
    test: make test
    timeout: 120
    deployment:
      minimum: 50
      maximum: 200
    scale:
      targets:
        cpu: 70
        memory: 90
      count: 1-1
      cpu: 512
      memory: 1024

timers:
  wpcron:
    command: "php /var/www/html/wp-cron.php"
    schedule: "* * * * *"
    service: cms
