resources:
  database:
    type: mariadb
    options:
      storage: 10
  #queue:
  #  type: redis

services:
  website:
    build:
      manifest: ./production/Dockerfile
      # command: bin/api
    environment:
      - ADMIN_URL
      - WP_CONTENT_CUSTOM_DIR
    health: /
    internal: false
    port: 8080
    resources:
      - database
    # - queue
    termination:
      grace: 45
    test: make test
    timeout: 120
    deployment:
      minimum: 50
      maximum: 200
    scale:
      count: 1
      cpu: 128
      memory: 256
