resources:
  database:
    type: mysql
    options:
      storage: 10
  #queue:
  #  type: redis

environment:
  - ADMIN_URL

services:
  website:
    domain: ${ADMIN_URL}
    build:
      manifest: ./production/Dockerfile
      # command: bin/api
    environment:
      - ADMIN_URL
      - DEBUG
      - OFFLOAD_AWS_REGION
      - OFFLOAD_AWS_BUCKET
      - OFFLOAD_AWS_ACCESS_ID
      - OFFLOAD_AWS_SECRET
      # NEW RELIC
      - NEW_RELIC_APP_NAME
      - NEW_RELIC_LICENSE_KEY
    health: /test.html
    internal: false
    port: 8080
    resources:
      - database
    # - queue
    termination:
      grace: 45
    test: make test
    timeout: 120
    deployment:
      minimum: 50
      maximum: 200
    scale:
      count: 1
      cpu: 512
      memory: 1024
