resources:
  database:
    type: mariadb
    options:
      storage: 10
  queue:
    type: redis

services:
  website:
    build:
      manifest: ./production/Dockerfile
      # command: bin/api
    environment:
      - APP_KEY
    health: /fpm-ping
    internal: false
    port: 80
    resources:
      - database
      - queue
    termination:
      grace: 45
    test: make test
    timeout: 120
    deployment:
      minimum: 50
      maximum: 200
    # Da capire la best practice per prod
    # cpu e memory NON sono scalabili da CLI
    scale:
      count: 1-2
      cpu: 128
      memory: 256
      targets:
        cpu: 70
        memory: 90
