version: '3.8'
networks:
#  labo-website-2021: null
  front-tier:
    external:
      name: front-tier

services:
  website:
    restart: unless-stopped
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/backend_nginx'
    networks:
      front-tier: null
    build:
      context: .
      dockerfile: ./production/Dockerfile
      args:
          CI_COMMIT_REF_NAME: '${CI_COMMIT_REF_NAME}'
          CI_REGISTRY: '${CI_REGISTRY}'
          CI_PROJECT_PATH: '${CI_PROJECT_PATH}'
          CI_REGISTRY_IMAGE: '${CI_REGISTRY_IMAGE}'
    environment:
      MYSQL_HOST: storage_mysql
      MYSQL_DATABASE: '${BACKEND_WORDPRESS_MYSQL_DATABASE}'
      MYSQL_USER: '${BACKEND_WORDPRESS_MYSQL_USER}'
      MYSQL_PASSWORD: '${BACKEND_WORDPRESS_MYSQL_PASSWORD}'
      ADMIN_URL: 'cms.${VIRTUAL_HOST}'
      SINK_AWS_REGION: '${BACKEND_WP_SINK_AWS_REGION}'
      SINK_AWS_BUCKET: '${BACKEND_WP_SINK_AWS_BUCKET}'
      SINK_AWS_ACCESS_ID: '${BACKEND_WP_SINK_AWS_ACCESS_ID}'
      SINK_AWS_SECRET: '${BACKEND_WP_SINK_AWS_SECRET}'
      SINK_AWS_UPLOADS_PATH: '${BACKEND_WP_SINK_AWS_UPLOADS_PATH}'
      SINK_KEEP_SITE_DOMAIN: '${BACKEND_WP_SINK_KEEP_SITE_DOMAIN}'
      SINK_CDN_ENDPOINT: '${BACKEND_WP_SINK_CDN_ENDPOINT}'
      SINK_HTTP_PROXY_URL: '${BACKEND_WP_SINK_HTTP_PROXY_URL}'
      SINK_HTTP_PROXY_PORT: '${BACKEND_WP_SINK_HTTP_PROXY_PORT}'
      POSTINO_CAFF_SMTP_SECURE: '${BACKEND_WP_POSTINO_CAFF_SMTP_SECURE}'
      POSTINO_CAFF_SMTP_PORT: '${BACKEND_WP_POSTINO_CAFF_SMTP_PORT}'
      POSTINO_CAFF_SMTP_SERVER: '${BACKEND_WP_POSTINO_CAFF_SMTP_SERVER}'
      POSTINO_CAFF_SMTP_USER: '${BACKEND_WP_POSTINO_CAFF_SMTP_USER}'
      POSTINO_CAFF_SMTP_PASSWORD: '${BACKEND_WP_POSTINO_CAFF_SMTP_PASSWORD}'
      POSTINO_CAFF_MAIL_SENDER: '${BACKEND_WP_POSTINO_CAFF_MAIL_SENDER}'
      POSTINO_CAFF_MAIL_SENDER_NAME: '${BACKEND_WP_POSTINO_CAFF_MAIL_SENDER_NAME}'
      WITH_REDIS: 1
      VIRTUAL_HOST: '${VIRTUAL_HOST}.localhost'
      VIRTUAL_PORT: 8080
    ports:
      - 8080:8080

  