version: '3.8'
networks:
  labo-website-2021: null
  front-tier:
    external:
      name: front-tier
services:
  backend_wordpress:
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/backend_wordpress'
    restart: unless-stopped
    volumes:
      - 'backend_media:/uploads'
    environment:
      WP_ENVIRONMENT_TYPE: '${WP_ENVIRONMENT_TYPE}'
      W3TC_PRO_DEV_MODE: '${W3TC_PRO_DEV_MODE}'
      W3TC_PRO_KEY: ${W3TC_PRO_KEY}
      MEMCACHED_URL: ${MEMCACHED_URL}
      DOMAIN: '${DOMAIN}'
      VIRTUAL_HOST: '${VIRTUAL_HOST},www.${VIRTUAL_HOST}'
      LETSENCRYPT_HOST: '${VIRTUAL_HOST},www.${VIRTUAL_HOST},cms.${VIRTUAL_HOST}'
      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
      DATABASE_URL: '${DATABASE_URL}'
      MYSQL_HOST: storage_mysql
      MYSQL_DATABASE: '${BACKEND_WORDPRESS_MYSQL_DATABASE}'
      MYSQL_USER: '${BACKEND_WORDPRESS_MYSQL_USER}'
      MYSQL_PASSWORD: '${BACKEND_WORDPRESS_MYSQL_PASSWORD}'
      ADMIN_URL: 'cms.${VIRTUAL_HOST}'
      WITH_FRONTEND: 1
      FRONTEND_URL: www.${VIRTUAL_HOST}
      OFFLOAD_AWS_REGION: '${AWS_REGION}'
      OFFLOAD_AWS_BUCKET: '${AWS_BUCKET}'
      OFFLOAD_AWS_ACCESS_ID: '${AWS_ACCESS_ID}'
      OFFLOAD_AWS_SECRET: '${AWS_SECRET}'
      POSTINO_CAFF_SMTP_SECURE: '${BACKEND_WP_POSTINO_CAFF_SMTP_SECURE}'
      POSTINO_CAFF_SMTP_PORT: '${BACKEND_WP_POSTINO_CAFF_SMTP_PORT}'
      POSTINO_CAFF_SMTP_SERVER: '${BACKEND_WP_POSTINO_CAFF_SMTP_SERVER}'
      POSTINO_CAFF_SMTP_USER: '${BACKEND_WP_POSTINO_CAFF_SMTP_USER}'
      POSTINO_CAFF_SMTP_PASSWORD: '${BACKEND_WP_POSTINO_CAFF_SMTP_PASSWORD}'
      POSTINO_CAFF_MAIL_SENDER: '${BACKEND_WP_POSTINO_CAFF_MAIL_SENDER}'
      POSTINO_CAFF_MAIL_SENDER_NAME: '${BACKEND_WP_POSTINO_CAFF_MAIL_SENDER_NAME}'
      DISABLE_WP_CRON: '${DISABLE_WP_CRON}'
      # NEW RELIC
      NEW_RELIC_APP_NAME: '${NEW_RELIC_APP_NAME}'
      NEW_RELIC_LICENSE_KEY: '${NEW_RELIC_LICENSE_KEY}'
      WITH_REDIS: 1
    networks:
      labo-website-2021:
        aliases:
          - '${VIRTUAL_HOST}'
      front-tier: null
  admin_backend_wordpress:
      image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/backend_wordpress'
      restart: unless-stopped
      volumes:
        - 'backend_media:/uploads'
      environment:
        WP_ENVIRONMENT_TYPE: '${WP_ENVIRONMENT_TYPE}'
        W3TC_PRO_DEV_MODE: '${W3TC_PRO_DEV_MODE}'
        W3TC_PRO_KEY: ${W3TC_PRO_KEY}
        MEMCACHED_URL: ${MEMCACHED_URL}
        DOMAIN: '${DOMAIN}'
        VIRTUAL_HOST: 'cms.${VIRTUAL_HOST}'
        LETSENCRYPT_HOST: '${VIRTUAL_HOST}'
        LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
        DATABASE_URL: '${DATABASE_URL}'
        MYSQL_HOST: storage_mysql
        MYSQL_DATABASE: '${BACKEND_WORDPRESS_MYSQL_DATABASE}'
        MYSQL_USER: '${BACKEND_WORDPRESS_MYSQL_USER}'
        MYSQL_PASSWORD: '${BACKEND_WORDPRESS_MYSQL_PASSWORD}'
        ADMIN_URL: 'cms.${VIRTUAL_HOST}'
        WITH_FRONTEND: 1
        FRONTEND_URL: www.${VIRTUAL_HOST}
        OFFLOAD_AWS_REGION: '${AWS_REGION}'
        OFFLOAD_AWS_BUCKET: '${AWS_BUCKET}'
        OFFLOAD_AWS_ACCESS_ID: '${AWS_ACCESS_ID}'
        OFFLOAD_AWS_SECRET: '${AWS_SECRET}'
        POSTINO_CAFF_SMTP_SECURE: '${BACKEND_WP_POSTINO_CAFF_SMTP_SECURE}'
        POSTINO_CAFF_SMTP_PORT: '${BACKEND_WP_POSTINO_CAFF_SMTP_PORT}'
        POSTINO_CAFF_SMTP_SERVER: '${BACKEND_WP_POSTINO_CAFF_SMTP_SERVER}'
        POSTINO_CAFF_SMTP_USER: '${BACKEND_WP_POSTINO_CAFF_SMTP_USER}'
        POSTINO_CAFF_SMTP_PASSWORD: '${BACKEND_WP_POSTINO_CAFF_SMTP_PASSWORD}'
        POSTINO_CAFF_MAIL_SENDER: '${BACKEND_WP_POSTINO_CAFF_MAIL_SENDER}'
        POSTINO_CAFF_MAIL_SENDER_NAME: '${BACKEND_WP_POSTINO_CAFF_MAIL_SENDER_NAME}'
        DISABLE_WP_CRON: '${DISABLE_WP_CRON}'
        # NEW RELIC
        NEW_RELIC_APP_NAME: '${NEW_RELIC_APP_NAME}'
        NEW_RELIC_LICENSE_KEY: '${NEW_RELIC_LICENSE_KEY}'
        WITH_REDIS: 1
      networks:
        labo-website-2021:
          aliases:
            - '${VIRTUAL_HOST}'
        front-tier: null
  backup_service:
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/backup_service'
    environment:
      MYSQL_HOST: storage_mysql
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      AWS_DEFAULT_REGION: '${BACKUP_AWS_DEFAULT_REGION}'
      AWS_SECRET_ACCESS_KEY: '${BACKUP_AWS_SECRET_ACCESS_KEY}'
      AWS_ACCESS_KEY_ID: '${BACKUP_AWS_ACCESS_KEY_ID}'
      AWS_S3_BUCKET: '${BACKUP_AWS_S3_BUCKET}'
    networks:
      - labo-website-2021
    restart: on-failure
  frontend_static_nginx:
    image: >-
      ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_static_nginx
    restart: unless-stopped
    networks:
      - front-tier
    environment:
      VIRTUAL_HOST: 'fe.${VIRTUAL_HOST}'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: '${VIRTUAL_HOST}'
      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
  frontend_storybook_nginx:
    image: >-
      ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_storybook_nginx
    restart: unless-stopped
    networks:
      - front-tier
    environment:
      VIRTUAL_HOST: 'storybook.${VIRTUAL_HOST}'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: 'storybook.${VIRTUAL_HOST}'
      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
    depends_on:
        - frontend_static_nginx
  storage_mysql:
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/storage_mysql'
    environment:
      MYSQL_HOST: storage_mysql
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      BACKEND_WORDPRESS_MYSQL_DATABASE: '${BACKEND_WORDPRESS_MYSQL_DATABASE}'
      BACKEND_WORDPRESS_MYSQL_USER: '${BACKEND_WORDPRESS_MYSQL_USER}'
      BACKEND_WORDPRESS_MYSQL_PASSWORD: '${BACKEND_WORDPRESS_MYSQL_PASSWORD}'
    volumes:
      - 'storage_mysql:/var/lib/mysql:rw'
    networks:
      - labo-website-2021
    restart: on-failure
  storage_redis:
    image: redis
    restart: unless-stopped
    networks:
      - labo-website-2021
  storage_memcached:
    image: memcached
    restart: unless-stopped
    networks:
      - labo-website-2021
volumes:
  backend_media: null
  storage_mysql: null
