version: '3'
services:
  frontend_bundler_vite:
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_bundler_vite'
    volumes:
      - '../frontend_bundler_vite/client/app:/app'
    command:
      - build
    environment:
      NODE_ENV: production
      ANALYZE: 1
