version: '3.8'
services:
  backend_wordpress:
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/backend_wordpress'
    build:
      context: ..
      cache_from:
        - '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/backend_wordpress'
      dockerfile: ./backend_wordpress/wordpress/docker/Dockerfile
      args:
          CI_COMMIT_REF_NAME: '${CI_COMMIT_REF_NAME}'
          CI_REGISTRY: '${CI_REGISTRY}'
          CI_PROJECT_PATH: '${CI_PROJECT_PATH}'
          CI_REGISTRY_IMAGE: '${CI_REGISTRY_IMAGE}'
          LB_API_TOKEN: ${LB_API_TOKEN}
          LB_API_URL: ${LB_API_URL}
    environment:
      WITH_WORDPRESS: 1
    depends_on:
      - frontend_bundler_vite
      - frontend_static
  admin_backend_wordpress:
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/backend_wordpress'
    build:
      context: ..
      cache_from:
         - '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/backend_wordpress'
      dockerfile: ./backend_wordpress/wordpress/docker/Dockerfile
      args:
          CI_COMMIT_REF_NAME: '${CI_COMMIT_REF_NAME}'
          CI_REGISTRY: '${CI_REGISTRY}'
          CI_PROJECT_PATH: '${CI_PROJECT_PATH}'
          CI_REGISTRY_IMAGE: '${CI_REGISTRY_IMAGE}'
          LB_API_TOKEN: ${LB_API_TOKEN}
          LB_API_URL: ${LB_API_URL}
    environment:
      WITH_WORDPRESS: 1
    depends_on:
      - frontend_bundler_vite
      - frontend_static
  backup_service:
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/backup_service'
    build:
      context: ..
      cache_from:
        - '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/backup_service'
      dockerfile: ./backup_service/docker/Dockerfile
  frontend_bundler_vite:
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_bundler_vite'
    build:
      context: ..
      cache_from:
        - '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_bundler_vite'
      dockerfile: ./frontend_bundler_vite/client/docker/Dockerfile
      args:
        LB_API_TOKEN: ${LB_API_TOKEN}
        LB_API_URL: ${LB_API_URL}
  frontend_static:
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_static'
    build:
      context: ..
      cache_from:
        - '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_static'
      dockerfile: ./frontend_static/client/docker/Dockerfile
      args:
        CI_COMMIT_REF_NAME: '${CI_COMMIT_REF_NAME}'
        CI_REGISTRY: '${CI_REGISTRY}'
        CI_PROJECT_PATH: '${CI_PROJECT_PATH}'
        CI_REGISTRY_IMAGE: '${CI_REGISTRY_IMAGE}'
    depends_on:
      - frontend_bundler_vite
  frontend_static_nginx:
    image: >-
      ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_static_nginx
    build:
      context: ..
      cache_from:
        - '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_static_nginx'
      dockerfile: ./frontend_static/nginx/docker/Dockerfile
      args:
        CI_COMMIT_REF_NAME: '${CI_COMMIT_REF_NAME}'
        CI_REGISTRY: '${CI_REGISTRY}'
        CI_PROJECT_PATH: '${CI_PROJECT_PATH}'
        CI_REGISTRY_IMAGE: '${CI_REGISTRY_IMAGE}'
    depends_on:
      - frontend_static
  frontend_storybook_new_nginx:
    image: >-
      ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_storybook_new_nginx
    build:
      context: ..
      cache_from:
        - '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_storybook_new_nginx'
      dockerfile: ./frontend_storybook_new/Dockerfile
      target: frontend_storybook_new_nginx
      args:
        CI_COMMIT_REF_NAME: '${CI_COMMIT_REF_NAME}'
        CI_REGISTRY: '${CI_REGISTRY}'
        CI_PROJECT_PATH: '${CI_PROJECT_PATH}'
        CI_REGISTRY_IMAGE: '${CI_REGISTRY_IMAGE}'
    depends_on:
      - frontend_storybook_new
  frontend_storybook_new:
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_storybook_new'
    build:
      context: ..
      cache_from:
        - '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_storybook_new'
      dockerfile: ./frontend_storybook_new/Dockerfile
      target: frontend_storybook_new
      args:
        CI_COMMIT_REF_NAME: '${CI_COMMIT_REF_NAME}'
        CI_REGISTRY: '${CI_REGISTRY}'
        CI_PROJECT_PATH: '${CI_PROJECT_PATH}'
        CI_REGISTRY_IMAGE: '${CI_REGISTRY_IMAGE}'
    depends_on:
      - frontend_static
  storage_mysql:
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/storage_mysql'
    build:
      context: ..
      cache_from:
        - '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/storage_mysql'
      dockerfile: ./storage_mysql/docker/Dockerfile
