version: '3'
networks:
  labo-website-2021: null
  front-tier:
    name: front-tier
services:
  backend_nginx:
    restart: unless-stopped
    networks:
      labo-website-2021:
        aliases:
          - 'cms.${VIRTUAL_HOST}.localhost'
      front-tier: null
    environment:
      VIRTUAL_HOST: 'cms.${VIRTUAL_HOST}.localhost'
    depends_on:
      - backend_wordpress
      - frontend_bundler
      - frontend_static
    volumes:
      - 'backend_wordpress:/var/www/html'
      - 'backend_media:/uploads'
      - >-
        ../backend_wordpress/wordpress/app/wp-content/themes:/var/www/html/wp-content-custom/themes
      - >-
        ../backend_wordpress/wordpress/app/wp-content/plugins:/var/www/html/wp-content-custom/plugins
      - >-
        ../backend_wordpress/wordpress/app/wp-config-custom:/var/www/html/wp-config-custom
      - >-
        ../frontend_bundler/client/app/dist/public:/var/www/html/wp-content-custom/themes/caffeina-theme/static
      - >-
        ../frontend_bundler/tommy/optimized:/var/www/html/wp-content-custom/themes/caffeina-theme/assets
      - >-
        ../frontend_static/client/app/views:/var/www/html/wp-content-custom/themes/caffeina-theme/views
  backend_wordpress:
    restart: unless-stopped
    depends_on:
      - storage_mysql
      - frontend_bundler
      - frontend_static
    volumes:
      - 'backend_wordpress:/var/www/html'
      - 'backend_media:/uploads'
      - >-
        ../backend_wordpress/wordpress/app/wp-content/themes:/var/www/html/wp-content-custom/themes
      - >-
        ../backend_wordpress/wordpress/app/wp-content/plugins:/var/www/html/wp-content-custom/plugins
      - >-
        ../backend_wordpress/wordpress/app/wp-config-custom:/var/www/html/wp-config-custom
      - >-
        ../frontend_bundler/client/app/dist/public:/var/www/html/wp-content-custom/themes/caffeina-theme/static
      - >-
        ../frontend_bundler/tommy/optimized:/var/www/html/wp-content-custom/themes/caffeina-theme/assets
      - >-
        ../frontend_static/client/app/views:/var/www/html/wp-content-custom/themes/caffeina-theme/views
    environment:
      MYSQL_HOST: storage_mysql
      MYSQL_DATABASE: '${BACKEND_WORDPRESS_MYSQL_DATABASE}'
      MYSQL_USER: '${BACKEND_WORDPRESS_MYSQL_USER}'
      MYSQL_PASSWORD: '${BACKEND_WORDPRESS_MYSQL_PASSWORD}'
      ADMIN_URL: 'cms.${VIRTUAL_HOST}.localhost'
      SINK_AWS_REGION: '${BACKEND_WP_SINK_AWS_REGION}'
      SINK_AWS_BUCKET: '${BACKEND_WP_SINK_AWS_BUCKET}'
      SINK_AWS_ACCESS_ID: '${BACKEND_WP_SINK_AWS_ACCESS_ID}'
      SINK_AWS_SECRET: '${BACKEND_WP_SINK_AWS_SECRET}'
      SINK_AWS_UPLOADS_PATH: '${BACKEND_WP_SINK_AWS_UPLOADS_PATH}'
      SINK_KEEP_SITE_DOMAIN: '${BACKEND_WP_SINK_KEEP_SITE_DOMAIN}'
      SINK_CDN_ENDPOINT: '${BACKEND_WP_SINK_CDN_ENDPOINT}'
      SINK_HTTP_PROXY_URL: '${BACKEND_WP_SINK_HTTP_PROXY_URL}'
      SINK_HTTP_PROXY_PORT: '${BACKEND_WP_SINK_HTTP_PROXY_PORT}'
      POSTINO_CAFF_SMTP_SECURE: '${BACKEND_WP_POSTINO_CAFF_SMTP_SECURE}'
      POSTINO_CAFF_SMTP_PORT: '${BACKEND_WP_POSTINO_CAFF_SMTP_PORT}'
      POSTINO_CAFF_SMTP_SERVER: '${BACKEND_WP_POSTINO_CAFF_SMTP_SERVER}'
      POSTINO_CAFF_SMTP_USER: '${BACKEND_WP_POSTINO_CAFF_SMTP_USER}'
      POSTINO_CAFF_SMTP_PASSWORD: '${BACKEND_WP_POSTINO_CAFF_SMTP_PASSWORD}'
      POSTINO_CAFF_MAIL_SENDER: '${BACKEND_WP_POSTINO_CAFF_MAIL_SENDER}'
      POSTINO_CAFF_MAIL_SENDER_NAME: '${BACKEND_WP_POSTINO_CAFF_MAIL_SENDER_NAME}'
      WITH_REDIS: 1
    networks:
      - labo-website-2021
  backup_service:
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/backup_service'
    environment:
      MYSQL_HOST: storage_mysql
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      AWS_DEFAULT_REGION: '${BACKUP_AWS_DEFAULT_REGION}'
      AWS_SECRET_ACCESS_KEY: '${BACKUP_AWS_SECRET_ACCESS_KEY}'
      AWS_ACCESS_KEY_ID: '${BACKUP_AWS_ACCESS_KEY_ID}'
      AWS_S3_BUCKET: '${BACKUP_AWS_S3_BUCKET}'
    networks:
      - labo-website-2021
    restart: on-failure
  frontend_browser-sync:
    restart: always
    image: >-
      ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_browser-sync
    build:
      context: ..
      dockerfile: ./frontend_bundler/browser-sync/docker/Dockerfile
    volumes:
      - '../frontend_bundler/client/app:/source'
      - >-
        ../frontend_bundler/browser-sync/docker/entrypoint.sh:/usr/bin/entrypoint
    networks:
      - labo-website-2021
      - front-tier
    environment:
      VIRTUAL_HOST: '${VIRTUAL_HOST}.localhost'
      VIRTUAL_PORT: 80
      PROXY: frontend_static_nginx
  frontend_bundler:
    tty: true
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_bundler'
    volumes:
      - '../frontend_bundler/client/app:/app'
      - '../frontend_bundler/client/docker/entrypoint.sh:/usr/bin/entrypoint'
    command:
      - dev
    environment:
      NODE_ENV: development
    networks:
      - labo-website-2021
      - front-tier
  frontend_tommy:
    image: 'kopiro/tommy:latest'
    volumes:
      - '../frontend_bundler/tommy/original:/src'
      - '../frontend_bundler/tommy/optimized:/dst'
      - '../frontend_bundler/tommy/config.json:/root/config.json'
    command:
      - '--src'
      - /src
      - '--dst'
      - /dst
      - '--config'
      - /root/config.json
      - '--watch'
    networks:
      - labo-website-2021
    logging:
      driver: none
  frontend_static:
    command:
      - dev
    tty: true
    environment:
      NODE_ENV: development
    volumes:
      - '../frontend_static/client/app:/app'
      - '../frontend_bundler/client/app/dist/public:/app/dist/bundle'
      - '../frontend_static/client/docker/entrypoint.sh:/usr/bin/entrypoint'
    networks:
      - labo-website-2021
  frontend_static_nginx:
    volumes:
      - '../frontend_static/client/app/dist/public:/var/static'
      - '../frontend_bundler/client/app/dist/public:/var/bundle'
      - '../frontend_bundler/tommy/optimized:/var/assets'
    networks:
      - labo-website-2021
      - front-tier
    environment:
      VIRTUAL_HOST: 'frontend_nginx.${VIRTUAL_HOST}.localhost'
      VIRTUAL_PORT: 80
    restart: unless-stopped
  frontend_storybook:
    command:
      - dev
    volumes:
      - '../frontend_storybook/storybook/app:/app'
      - '../frontend_static/client/app/views:/app/views'
      - '../frontend_static/client/app/fixtures:/app/fixtures'
      - '../frontend_bundler/client/app/scripts:/app/scripts'
      - '../frontend_bundler/client/app/styles:/app/styles'
      - '../frontend_bundler/tommy/optimized:/app/public/assets'
    networks:
      - labo-website-2021
      - front-tier
    environment:
      VIRTUAL_HOST: 'storybook.${VIRTUAL_HOST}.localhost'
      VIRTUAL_PORT: 6006
    depends_on:
      - frontend_static
  storage_mysql:
    restart: on-failure
    environment:
      MYSQL_HOST: storage_mysql
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      BACKEND_WORDPRESS_MYSQL_DATABASE: '${BACKEND_WORDPRESS_MYSQL_DATABASE}'
      BACKEND_WORDPRESS_MYSQL_USER: '${BACKEND_WORDPRESS_MYSQL_USER}'
      BACKEND_WORDPRESS_MYSQL_PASSWORD: '${BACKEND_WORDPRESS_MYSQL_PASSWORD}'
    ports:
      - "3308:3306"
    networks:
      - labo-website-2021
      - front-tier
    volumes:
      - 'storage_mysql:/var/lib/mysql:rw'
  storage_redis:
    image: redis
    restart: unless-stopped
    networks:
      - labo-website-2021
volumes:
  backend_wordpress: null
  backend_media: null
  storage_mysql: null
