version: '3.8'
networks:
  labo-website-2021: null
  front-tier:
    external:
      name: front-tier
services:
  backend_wordpress:
    restart: unless-stopped
    build:
      target: dev
    networks:
      labo-website-2021:
        aliases:
          - '${VIRTUAL_HOST}.localhost'
      front-tier: null
    environment:
      DEBUG: '${DEBUG}'
      W3TC_PRO_DEV_MODE: '${W3TC_PRO_DEV_MODE}'
      W3TC_PRO_KEY: ${W3TC_PRO_KEY}
      MEMCACHED_URL: ${MEMCACHED_URL}
      WP_CONTENT_CUSTOM_DIR: '${WP_CONTENT_CUSTOM_DIR}'
      VIRTUAL_HOST: '${VIRTUAL_HOST}.localhost,www.${VIRTUAL_HOST}.localhost'
      DATABASE_URL: '${DATABASE_URL}'
      MYSQL_HOST: storage_mysql
      MYSQL_DATABASE: '${BACKEND_WORDPRESS_MYSQL_DATABASE}'
      MYSQL_USER: '${BACKEND_WORDPRESS_MYSQL_USER}'
      MYSQL_PASSWORD: '${BACKEND_WORDPRESS_MYSQL_PASSWORD}'
      ADMIN_URL: 'cms.${VIRTUAL_HOST}.localhost'
      WITH_FRONTEND: 1
      FRONTEND_URL: www.${VIRTUAL_HOST}.localhost
      OFFLOAD_AWS_REGION: '${AWS_REGION}'
      OFFLOAD_AWS_BUCKET: '${AWS_BUCKET}'
      OFFLOAD_AWS_ACCESS_ID: '${AWS_ACCESS_ID}'
      OFFLOAD_AWS_SECRET: '${AWS_SECRET}'
      POSTINO_CAFF_SMTP_SECURE: '${BACKEND_WP_POSTINO_CAFF_SMTP_SECURE}'
      POSTINO_CAFF_SMTP_PORT: '${BACKEND_WP_POSTINO_CAFF_SMTP_PORT}'
      POSTINO_CAFF_SMTP_SERVER: '${BACKEND_WP_POSTINO_CAFF_SMTP_SERVER}'
      POSTINO_CAFF_SMTP_USER: '${BACKEND_WP_POSTINO_CAFF_SMTP_USER}'
      POSTINO_CAFF_SMTP_PASSWORD: '${BACKEND_WP_POSTINO_CAFF_SMTP_PASSWORD}'
      POSTINO_CAFF_MAIL_SENDER: '${BACKEND_WP_POSTINO_CAFF_MAIL_SENDER}'
      POSTINO_CAFF_MAIL_SENDER_NAME: '${BACKEND_WP_POSTINO_CAFF_MAIL_SENDER_NAME}'
      WITH_REDIS: 1
      DISABLE_WP_CRON: '${DISABLE_WP_CRON}'
    depends_on:
      - storage_mysql
      - frontend_bundler
      - frontend_static
    volumes:
      - 'backend_media:/uploads'
      - >-
        ../backend_wordpress/wordpress/app/wp-content/themes:/var/www/html/wp-content-custom/themes
      - >-
        ../backend_wordpress/wordpress/app/wp-content/w3tc-config:/var/www/html/wp-content-custom/w3tc-config
      - >-
        ../backend_wordpress/wordpress/app/wp-content/plugins:/var/www/html/wp-content-custom/plugins
      - >-
        ../backend_wordpress/wordpress/app/wp-content/themes/caffeina-theme/packages:/var/www/html/wp-content-custom/themes/caffeina-theme/packages
      - >-
        ../backend_wordpress/wordpress/app/wp-config-custom:/var/www/html/wp-config-custom
      - >-
        ../frontend_bundler/client/app/dist/public:/var/www/html/wp-content-custom/themes/caffeina-theme/static
      - >-
        ../frontend_bundler/tommy/optimized:/var/www/html/wp-content-custom/themes/caffeina-theme/assets
      - >-
        ../frontend_static/client/app/views:/var/www/html/wp-content-custom/themes/caffeina-theme/views
      - >-
        ../backend_wordpress/wordpress/app/wp-content/languages:/var/www/html/wp-content-custom/languages
      - >-
        ../backend_wordpress/nginx/redirect/labo.map:/etc/nginx/redirect/labo.map
      - >-
        ../backend_wordpress/nginx/nginx.conf:/etc/nginx/nginx.conf
  admin_backend_wordpress:
    restart: unless-stopped
    build:
      target: dev
    networks:
      labo-website-2021:
        aliases:
          - 'cms.${VIRTUAL_HOST}.localhost'
      front-tier: null
    environment:
      DEBUG: '${DEBUG}'
      W3TC_PRO_DEV_MODE: '${W3TC_PRO_DEV_MODE}'
      W3TC_PRO_KEY: ${W3TC_PRO_KEY}
      MEMCACHED_URL: ${MEMCACHED_URL}
      WP_CONTENT_CUSTOM_DIR: '${WP_CONTENT_CUSTOM_DIR}'
      VIRTUAL_HOST: 'cms.${VIRTUAL_HOST}.localhost'
      DATABASE_URL: '${DATABASE_URL}'
      MYSQL_HOST: storage_mysql
      MYSQL_DATABASE: '${BACKEND_WORDPRESS_MYSQL_DATABASE}'
      MYSQL_USER: '${BACKEND_WORDPRESS_MYSQL_USER}'
      MYSQL_PASSWORD: '${BACKEND_WORDPRESS_MYSQL_PASSWORD}'
      ADMIN_URL: 'cms.${VIRTUAL_HOST}.localhost'
      WITH_FRONTEND: 1
      FRONTEND_URL: www.${VIRTUAL_HOST}.localhost
      OFFLOAD_AWS_REGION: '${AWS_REGION}'
      OFFLOAD_AWS_BUCKET: '${AWS_BUCKET}'
      OFFLOAD_AWS_ACCESS_ID: '${AWS_ACCESS_ID}'
      OFFLOAD_AWS_SECRET: '${AWS_SECRET}'
      POSTINO_CAFF_SMTP_SECURE: '${BACKEND_WP_POSTINO_CAFF_SMTP_SECURE}'
      POSTINO_CAFF_SMTP_PORT: '${BACKEND_WP_POSTINO_CAFF_SMTP_PORT}'
      POSTINO_CAFF_SMTP_SERVER: '${BACKEND_WP_POSTINO_CAFF_SMTP_SERVER}'
      POSTINO_CAFF_SMTP_USER: '${BACKEND_WP_POSTINO_CAFF_SMTP_USER}'
      POSTINO_CAFF_SMTP_PASSWORD: '${BACKEND_WP_POSTINO_CAFF_SMTP_PASSWORD}'
      POSTINO_CAFF_MAIL_SENDER: '${BACKEND_WP_POSTINO_CAFF_MAIL_SENDER}'
      POSTINO_CAFF_MAIL_SENDER_NAME: '${BACKEND_WP_POSTINO_CAFF_MAIL_SENDER_NAME}'
      WITH_REDIS: 1
      DISABLE_WP_CRON: '${DISABLE_WP_CRON}'
    depends_on:
      - storage_mysql
      - frontend_bundler
      - frontend_static
    volumes:
      - 'backend_media:/uploads'
      - >-
        ../backend_wordpress/wordpress/app/wp-content/themes:/var/www/html/wp-content-custom/themes
      - >-
        ../backend_wordpress/wordpress/app/wp-content/w3tc-config:/var/www/html/wp-content-custom/w3tc-config
      - >-
        ../backend_wordpress/wordpress/app/wp-content/plugins:/var/www/html/wp-content-custom/plugins
      - >-
        ../backend_wordpress/wordpress/app/wp-content/themes/caffeina-theme/packages:/var/www/html/wp-content-custom/themes/caffeina-theme/packages
      - >-
        ../backend_wordpress/wordpress/app/wp-config-custom:/var/www/html/wp-config-custom
      - >-
        ../frontend_bundler/client/app/dist/public:/var/www/html/wp-content-custom/themes/caffeina-theme/static
      - >-
        ../frontend_bundler/tommy/optimized:/var/www/html/wp-content-custom/themes/caffeina-theme/assets
      - >-
        ../frontend_static/client/app/views:/var/www/html/wp-content-custom/themes/caffeina-theme/views
      - >-
        ../backend_wordpress/wordpress/app/wp-content/languages:/var/www/html/wp-content-custom/languages
      - >-
        ../backend_wordpress/nginx/redirect/labo.map:/etc/nginx/redirect/labo.map
      - >-
        ../backend_wordpress/nginx/nginx.conf:/etc/nginx/nginx.conf
  backup_service:
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/backup_service'
    environment:
      MYSQL_HOST: storage_mysql
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      AWS_DEFAULT_REGION: '${BACKUP_AWS_DEFAULT_REGION}'
      AWS_SECRET_ACCESS_KEY: '${BACKUP_AWS_SECRET_ACCESS_KEY}'
      AWS_ACCESS_KEY_ID: '${BACKUP_AWS_ACCESS_KEY_ID}'
      AWS_S3_BUCKET: '${BACKUP_AWS_S3_BUCKET}'
    networks:
      - labo-website-2021
    restart: on-failure
  frontend_browser-sync:
    restart: always
    image: >-
      ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_browser-sync
    build:
      context: ..
      dockerfile: ./frontend_bundler/browser-sync/docker/Dockerfile
    volumes:
      - '../frontend_bundler/client/app:/source'
      - >-
        ../frontend_bundler/browser-sync/docker/entrypoint.sh:/usr/bin/entrypoint
    networks:
      - labo-website-2021
      - front-tier
    environment:
      VIRTUAL_HOST: 'fe.${VIRTUAL_HOST}.localhost'
      VIRTUAL_PORT: 80
      LB_API_TOKEN: ${LB_API_TOKEN}
      LB_API_URL: ${LB_API_URL}
      PROXY: frontend_static_nginx
  frontend_bundler:
    tty: true
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_bundler'
    volumes:
      - '../frontend_bundler/client/app:/app'
      - '../frontend_bundler/client/docker/entrypoint.sh:/usr/bin/entrypoint'
    command:
      - dev
    environment:
      NODE_ENV: development
      LB_API_TOKEN: ${LB_API_TOKEN}
      LB_API_URL: ${LB_API_URL}
    networks:
      - labo-website-2021
      - front-tier
  frontend_tommy:
    image: 'kopiro/tommy:latest'
    volumes:
      - '../frontend_bundler/tommy/original:/src'
      - '../frontend_bundler/tommy/optimized:/dst'
      - '../frontend_bundler/tommy/config.json:/root/config.json'
    command:
      - '--src'
      - /src
      - '--dst'
      - /dst
      - '--config'
      - /root/config.json
      - '--watch'
    networks:
      - labo-website-2021
    logging:
      driver: none
  frontend_static:
    command:
      - dev
    tty: true
    environment:
      NODE_ENV: development
    volumes:
      - '../frontend_static/client/app:/app'
      - '../frontend_bundler/client/app/dist/public:/app/dist/bundle'
      - '../frontend_static/client/docker/entrypoint.sh:/usr/bin/entrypoint'
    networks:
      - labo-website-2021
  frontend_static_nginx:
    volumes:
      - '../frontend_static/client/app/dist/public:/var/static'
      - '../frontend_bundler/client/app/dist/public:/var/bundle'
      - '../frontend_bundler/tommy/optimized:/var/assets'
    networks:
      - labo-website-2021
      - front-tier
    environment:
      VIRTUAL_HOST: 'frontend_nginx.${VIRTUAL_HOST}.localhost'
      VIRTUAL_PORT: 80
    restart: unless-stopped
  frontend_storybook:
    command:
      - dev
    volumes:
      - '../frontend_storybook/storybook/app:/app'
      - '../frontend_static/client/app/views:/app/views'
      - '../frontend_static/client/app/fixtures:/app/fixtures'
      - '../frontend_bundler/client/app/scripts:/app/scripts'
      - '../frontend_bundler/client/app/styles:/app/styles'
      - '../frontend_bundler/tommy/optimized:/app/public/assets'
    networks:
      - labo-website-2021
      - front-tier
    environment:
      VIRTUAL_HOST: 'storybook.${VIRTUAL_HOST}.localhost'
      VIRTUAL_PORT: 6006
    depends_on:
      - frontend_static
  storage_mysql:
    restart: on-failure
    environment:
      MYSQL_HOST: storage_mysql
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      BACKEND_WORDPRESS_MYSQL_DATABASE: '${BACKEND_WORDPRESS_MYSQL_DATABASE}'
      BACKEND_WORDPRESS_MYSQL_USER: '${BACKEND_WORDPRESS_MYSQL_USER}'
      BACKEND_WORDPRESS_MYSQL_PASSWORD: '${BACKEND_WORDPRESS_MYSQL_PASSWORD}'
    ports:
      - "3308:3306"
    networks:
      - labo-website-2021
      - front-tier
    volumes:
      - 'storage_mysql:/var/lib/mysql:rw'
  storage_redis:
    image: redis
    restart: unless-stopped
    networks:
      - labo-website-2021
  storage_memcached:
    image: memcached
    restart: unless-stopped
    networks:
      - labo-website-2021
volumes:
  backend_media: null
  storage_mysql: null
