version: '3'
services:
  frontend_static:
    tty: true
    command:
      - build
    environment:
      NODE_ENV: production
      ENABLE_ROBOTS: 1
    volumes:
      - '../frontend_static/client/app:/app'
      - '../frontend_bundler_vite/client/app/dist:/app/dist'
  frontend_bundler_vite:
    environment:
      NODE_ENV: production
    command:
      - build
    volumes:
      - '../frontend_bundler_vite/client/app:/app'
  frontend_storybook_new:
    command:
      - build
    volumes:
      - '../frontend_storybook_new/storybook/app:/app'
      - '../frontend_static/client/app/views:/app/views'
      - '../frontend_static/client/app/fixtures:/app/fixtures'
      - '../frontend_bundler_vite/client/app/src/scripts:/app/scripts'
      - '../frontend_bundler_vite/client/app/src/styles:/app/styles'
      - '../frontend_bundler_vite/tommy/optimized:/app/public/assets'
