FROM registry.caffeina.co/devops/nador-images/wordpress-base/master/backend_wordpress

COPY ./backend_wordpress/wordpress/app/wp-content /root/src/wp-content
COPY ./backend_wordpress/wordpress/app/wp-config-custom /root/src/wp-config-custom
