FROM registry.caffeina.co/devops/nador-images/nginx-base/master/nginx:latest

COPY ./backend_wordpress/nginx/config/sites-enabled/wordpress.conf /etc/nginx/sites-enabled/
COPY ./backend_wordpress/nginx/config/nginx.conf /etc/nginx/

